------------------//CONSTANTS
local cartGameplayConfig = table.freeze({
	flowMaximum = 100,
	flowCoinReward = 2,
	flowRiskCoinReward = 4,
	flowChainBonus = 10,
	flowTiltReward = 6,
	flowLandingReward = 12,
	flowLaunchRewardMaximum = 8,
	flowDecayDelay = 2.5,
	flowDecayRate = 5,
	overdriveDuration = 5,
	jumpEnergyMaximum = 100,
	jumpEnergyRegenerationRate = 24,
	jumpMaximumEnergyCost = 100,
	jumpMinimumInterval = 0.35,
	perfectLandingEnergyRefund = 15,
	obstacleCriticalScale = 2.1,
	obstacleCriticalDamage = 3,
	rollingBarrelAttribute = "IsRollingBarrel",
	rollingBarrelElapsedAttribute = "RollingBarrelElapsed",
	rollingBarrelBoundsAttribute = "RollingBarrelBoundsFromPivot",
	rollingBarrelTargetAttribute = "RollingBarrelTargetPosition",
	rollingBarrelDropAttribute = "RollingBarrelDropPosition",
	rollingBarrelDirectionAttribute = "RollingBarrelDirection",
	rollingBarrelNormalAttribute = "RollingBarrelNormal",
	rollingBarrelSpeedAttribute = "RollingBarrelSpeed",
	rollingBarrelSpinAttribute = "RollingBarrelSpinSpeed",
	rollingBarrelChance = 0.1,
	rollingBarrelDropHeight = 8,
	rollingBarrelDropDuration = 0.38,
	rollingBarrelSpeed = 36,
	rollingBarrelSpinSpeed = 13,
	rollingBarrelLifetime = 5.2,
	rollingBarrelFadeDuration = 0.24,
})

------------------//INIT
return cartGameplayConfig
