------------------//VARIABLES
export type WeaponDefinition = {
	id: string,
	toolName: string,
	hotbarImage: string?,
	hasPinAnimation: boolean,
	previewColor: Color3,
	maxThrowDistance: number,
	minimumFlightDuration: number,
	maximumFlightDuration: number,
	pinDuration: number,
	releaseDelay: number,
	throwAnimationDuration: number,
	cooldownDuration: number,
	blastRadius: number,
	horizontalKnockbackSpeed: number,
	verticalKnockbackSpeed: number,
	spinDuration: number,
	trapLifetime: number,
}

local weaponDefinitions: {[string]: WeaponDefinition} = {
	Grenade = {
		id = "Grenade",
		toolName = "Granade",
		hotbarImage = "",
		hasPinAnimation = true,
		previewColor = Color3.fromRGB(255, 120, 47),
		maxThrowDistance = 115,
		minimumFlightDuration = 0.72,
		maximumFlightDuration = 1.35,
		pinDuration = 0.62,
		releaseDelay = 0.16,
		throwAnimationDuration = 0.75,
		cooldownDuration = 0.8,
		blastRadius = 20,
		horizontalKnockbackSpeed = 82,
		verticalKnockbackSpeed = 54,
		spinDuration = 0,
		trapLifetime = 0,
	},
	Banana = {
		id = "Banana",
		toolName = "Banana",
		hotbarImage = "rbxassetid://78445436248608",
		hasPinAnimation = false,
		previewColor = Color3.fromRGB(255, 225, 54),
		maxThrowDistance = 90,
		minimumFlightDuration = 0.62,
		maximumFlightDuration = 1.18,
		pinDuration = 0,
		releaseDelay = 0.14,
		throwAnimationDuration = 0.75,
		cooldownDuration = 0.8,
		blastRadius = 0,
		horizontalKnockbackSpeed = 0,
		verticalKnockbackSpeed = 0,
		spinDuration = 2.4,
		trapLifetime = 24,
	},
}

------------------//INIT
return table.freeze({
	remoteName = "WeaponThrowRequest",
	weaponsFolderName = "Weapons",
	projectileTemplatesFolderName = "Projectiles",
	bananaProjectileTemplateName = "BananaPeel",
	projectilesFolderName = "WeaponProjectiles",
	trapsFolderName = "WeaponTraps",
	weaponIdAttribute = "WeaponId",
	hotbarImageAttribute = "HotbarImage",
	allowRampAnimationAttribute = "AllowDuringRampSlide",
	spinUntilAttribute = "CartSpinUntil",
	externalLaunchSequenceAttribute = "CartExternalLaunchSequence",
	isRampSlidingAttribute = "IsRampSliding",
	rampModeStateAttribute = "RampModeState",
	rampAirborneVelocityAttribute = "RampAirborneVelocity",
	cartJumpActiveAttribute = "CartJumpActive",
	chargeState = "Charge",
	airborneState = "Airborne",
	aimActionName = "WeaponAim",
	aimActionTitle = "MIRAR",
	aimActionPosition = UDim2.fromScale(0.84, 0.68),
	aimRayDistance = 500,
	aimSurfaceSearchHeight = 70,
	aimSurfaceSearchDistance = 180,
	trajectorySegmentCount = 18,
	trajectoryThickness = 0.12,
	targetMarkerSize = 4,
	spinAngularSpeed = math.rad(900),
	definitions = table.freeze(weaponDefinitions),
})
